### ISSUE TITLE
Shows unused key when used in ternary

### ISSUE THREAD

**Issue by aoumiri** [simplabs/ember-intl-analyzer#143]
When a ternary is used, the translation in the first block is recognized while the second is not, thus failing with the linter job.

Here is a simplified example where the intlService is injected as a parameter function:

```js
function switchKey(intlService, condition) {
  return intlService.t(condition ? 'detected.key': 'ignored.key');
}
```

I had to change a bit the code so that the second key is recognized, like that:

```js
return condition
   ? intlService.t('detected.key')
   : intlService.t('ignored.key');
```

Is it a bug, or does the analyzer don't handle conditional keys ?

**Comment by Turbo87** [comment]
you can find the implementation at https://github.com/simplabs/ember-intl-analyzer/blob/master/index.js#L136.

basically, it only detects `something.t('someString', ...)`, but it is not aware of any conditions or other more complicated structures like that.

**Comment by Mikek2252** [comment]
Worth mentioning that i just came across this problem in the template earlier today with an using an `if`

**Comment by Mikek2252** [comment]
ternarys can now be used in the `this.intl.t(...` helper and conditionals within the t template helper can also be used as of 3.1.0 release so am closing this issue.
