### ISSUE TITLE
Support for CJS config file?

### ISSUE THREAD

**Issue by bertdeblock** [simplabs/ember-intl-analyzer#256]
Hi! Would it be possible to also support a config file with a CJS export? All JS files located under `/config` contain CJS exports and are also linted with the node plugin for EsLint. Linting (with the default Ember EsLint configuration) fails when creating a configuration file for ember-intl-analyzer as suggested in the docs. At the moment I just ignore that file. It's probably a stupid request, but support for CJS export would be slightly nicer and more consistent with the rest.

Thanks!

**Comment by Turbo87** [comment]
I think that should already be supported due to our use of https://github.com/standard-things/esm

**Comment by bertdeblock** [comment]
Isn't that package meant for importing ES modules in Node land? I've tried the following, but it doesn't work:

```javascript
module.exports = {
  whitelist: []
}
```

**Comment by Turbo87** [comment]
> Isn't that package meant for importing ES modules in Node land?

yes, but their README says "By default, 💯 percent CJS interoperability is enabled so you can get stuff done." so I was assuming that it would just work with the snippet you posted above. if not I'm open to merging PRs that make both work.

**Comment by bertdeblock** [comment]
Aha okay, I think I know what's up. I'm guessing `.default` on [L86](https://github.com/simplabs/ember-intl-analyzer/blob/master/index.js#L86) is causing `TypeError: Cannot read property 'whitelist' of undefined`.
I thought it was the import that didn't work.
