### ISSUE TITLE
Typescript file support ?

### ISSUE THREAD

**Issue by oliverlj** [simplabs/ember-intl-analyzer#435]
Can typescript support can be added ?

**Comment by Mikek2252** [comment]
Hey @oliverlj! as of the latest release https://github.com/simplabs/ember-intl-analyzer/releases/tag/v4.4.0 typescript is now supported check out [here](https://github.com/simplabs/ember-intl-analyzer#babelparserplugins-extensions) for how to set up you config file. 

Feel free to reopen or create another issues you experience any issues with it.
